cask_args appdir: "/Applications"

# Tap
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
# tap "hashicorp/tap" # for waypoint
tap "sanemat/font" # for Ricty
tap "yoheimuta/protolint" # for protolint

# Terminal
brew "bash-completion"
brew "bat"
brew "fzf"
brew "gcc"
brew "zoxide"
brew "exa"
brew "fd"
brew "jq"
brew "starship"
brew "ripgrep"
brew "procs"
brew "bandwhich"
brew "grpcurl"
brew "cjbassi/ytop/ytop"
cask "iterm2"

# Programming Languages
brew "goenv", args: ['HEAD']
# brew "rbenv", args: ['HEAD']
brew "pyenv", args: ['HEAD']
brew "protolint"

# Programming Fonts
brew "ricty"
cask "font-ricty-diminished"

# DataBase
brew "postgresql"
cask "postico"

# Git
brew "gh"
brew "ghq"
brew "git"
brew "tig"

# Docker
brew "docker"
brew "podman"

# k8s
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx"
brew "kubespy"
brew "stern"
brew "kind" # Kubernetes in Docker
brew "helm"
brew "kustomize"
brew "kubeseal" # https://github.com/bitnami-labs/sealed-secrets
brew "kubevela" # https://github.com/oam-dev/kubevela
# brew "skaffold"
brew "derailed/k9s/k9s"
brew "tektoncd-cli"
cask "lens"

# ansible
brew "ansible"

# terraform
brew "tfenv"
brew "tflint"
# brew "hashicorp/tap/waypoint" # https://www.waypointproject.io/docs/intro
# brew "terragrunt"  # automatic install specific terraform version

# cloud
cask "google-cloud-sdk"
brew "awscli"
cask "aws-vault"

# vagrant
cask "vagrant"
cask "virtualbox"

# Applications
cask "google-chrome"
cask "slack"
cask "visual-studio-code"

# Tools
cask "clipy"
cask "google-japanese-ime"
