brew "awscli"
brew "eza" # awesome ls
brew "fd"  # awesome find
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "grpcurl"
brew "helm"
brew "jq"
brew "k9s"
brew "kind"
brew "kubernetes-cli"
brew "kubectx"
brew "kustomize"
brew "ripgrep"
brew "stern"
brew "tfenv"
brew "tig"
brew "uv"
cask "docker-desktop"
cask "gcloud-cli"
cask "google-chrome"
cask "google-japanese-ime"
cask "raycast"
cask "slack"
cask "visual-studio-code"
cask "warp"
